name: Generate data and build dashboard

on:
  schedule:
    # Every Friday at midnight
    - cron: '0 0 * * FRI'
  workflow_dispatch:

jobs:
  build:
    name: Generate & build dashboard
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check-out the repository
        uses: actions/checkout@v4

      - name: Update dependencies
        run: npm run bump

      - name: Compute feature data
        run: npm run generate

      - name: Retrieve latest WPT and Test262 runs and fetch test results
        run: |
          npm run update-dates
          npm run fetch-results

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Weekly regen" --allow-empty
          git push origin main

      - name: Generate site
        run: npm run build-site

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
